# Generated by Django 2.1.1 on 2018-10-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20181002_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='org',
        ),
    ]
