# Generated by Django 2.1.1 on 2018-10-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_remove_todo_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='todoList', to='rest_api.Organisation'),
            preserve_default=False,
        ),
    ]
